// verify-users — turn a feedback-form export into verified on-chain evidence.
//
// L5/L6 are judged on real users, and the rule that catches people out is that
// a wallet address alone proves nothing: anyone can paste one. So every row has
// to carry a transaction hash, and this script checks that the hash really is a
// `placeBid` call on OUR contract, via the public Preprod indexer.
//
// Nothing here trusts the form. A row is verified only if the indexer says so.
//
//   MIDNIGHT_NETWORK=preprod npm run verify-users -- users.csv
//   npm run verify-users -- users.csv --markdown ../docs/USERS.md
//
// The CSV is whatever the form exports, as long as it has a header row with a
// wallet-address column and a tx-hash column. Column names are matched loosely
// because form builders rename them; see COLUMN_HINTS.
//
// USERS.md must be generated by this script, never written by hand — a
// hand-maintained table is exactly the unverifiable evidence the rules reject.

import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

import { resolveNetwork } from './wallet.js'

const CONTRACT =
  process.env.CONTRACT_ADDRESS ??
  'f81e44eaf0acc9f92c80aba03c6ac822c38004d09b9c4d5d5ba330b4d9ec66dc'

const HEX_64 = /^[0-9a-f]{64}$/i

type Verdict =
  | 'verified'
  | 'not-found'
  | 'wrong-contract'
  | 'not-a-bid'
  | 'malformed-hash'
  | 'missing-hash'

type Row = {
  address: string
  txHash: string
  dropId: string
  date: string
}

type Result = Row & {
  verdict: Verdict
  entryPoint: string | null
  block: number | null
  detail: string
}

const COLUMN_HINTS = {
  address: ['wallet', 'address', 'mn_addr', 'wallet address'],
  tx: ['tx', 'hash', 'transaction', 'txid', 'tx hash'],
  drop: ['drop', 'which drop', 'drop id'],
  date: ['date', 'timestamp', 'submitted', 'time'],
}

/** Minimal CSV reader: handles quoted fields and embedded commas. */
const parseCsv = (text: string): string[][] => {
  const rows: string[][] = []
  let row: string[] = []
  let field = ''
  let quoted = false
  for (let i = 0; i < text.length; i += 1) {
    const c = text[i]
    if (quoted) {
      if (c === '"') {
        if (text[i + 1] === '"') { field += '"'; i += 1 } else quoted = false
      } else field += c
      continue
    }
    if (c === '"') quoted = true
    else if (c === ',') { row.push(field); field = '' }
    else if (c === '\n') { row.push(field); rows.push(row); row = []; field = '' }
    else if (c !== '\r') field += c
  }
  if (field.length > 0 || row.length > 0) { row.push(field); rows.push(row) }
  return rows.filter((r) => r.some((c) => c.trim() !== ''))
}

const findColumn = (headers: string[], hints: string[]): number =>
  headers.findIndex((h) => {
    const low = h.trim().toLowerCase()
    return hints.some((hint) => low.includes(hint))
  })

const toRows = (csv: string): Row[] => {
  const table = parseCsv(csv)
  if (table.length < 2) throw new Error('CSV needs a header row and at least one data row.')
  const headers = table[0]
  const iAddr = findColumn(headers, COLUMN_HINTS.address)
  const iTx = findColumn(headers, COLUMN_HINTS.tx)
  if (iAddr < 0 || iTx < 0) {
    throw new Error(
      `Could not find a wallet column and a tx-hash column in: ${headers.join(', ')}`,
    )
  }
  const iDrop = findColumn(headers, COLUMN_HINTS.drop)
  const iDate = findColumn(headers, COLUMN_HINTS.date)
  return table.slice(1).map((r) => ({
    address: (r[iAddr] ?? '').trim(),
    txHash: (r[iTx] ?? '').trim().replace(/^0x/, ''),
    dropId: iDrop >= 0 ? (r[iDrop] ?? '').trim() : '',
    date: iDate >= 0 ? (r[iDate] ?? '').trim() : '',
  }))
}

const gql = async (endpoint: string, query: string, variables: unknown) => {
  const res = await fetch(endpoint, {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ query, variables }),
  })
  return (await res.json()) as any
}

const TX_QUERY = `query($h: HexEncoded!) {
  transactions(offset: { hash: $h }) {
    hash
    block { height timestamp }
    contractActions { __typename address ... on ContractCall { entryPoint } }
  }
}`

/**
 * Entry points come back differently depending on the query: `contractAction`
 * hex-encodes them, `transactions` returns the plain name. Hex-decoding a plain
 * name silently produces garbage — which classified real `placeBid` calls as
 * "not a bid" and would have thrown away genuine user evidence. So decode only
 * when the value really is hex.
 */
const decodeEntryPoint = (value: string | null | undefined): string | null => {
  if (!value) return null
  const looksHex = /^[0-9a-f]+$/i.test(value) && value.length % 2 === 0
  if (!looksHex) return value
  const decoded = Buffer.from(value, 'hex').toString('utf8')
  return /^[\x20-\x7e]+$/.test(decoded) ? decoded : value
}

const verify = async (endpoint: string, row: Row): Promise<Result> => {
  const base = { ...row, entryPoint: null, block: null }
  if (!row.txHash) return { ...base, verdict: 'missing-hash', detail: 'no tx hash supplied' }
  if (!HEX_64.test(row.txHash)) {
    return {
      ...base,
      verdict: 'malformed-hash',
      detail: `not a 64-char hash (got ${row.txHash.length} chars) — the house scripts print a 69-char identifier, which is not the hash`,
    }
  }

  const data = await gql(endpoint, TX_QUERY, { h: row.txHash.toLowerCase() })
  const tx = data?.data?.transactions?.[0]
  if (!tx) return { ...base, verdict: 'not-found', detail: 'no such transaction on this network' }

  const block = tx.block?.height ?? null
  const actions: any[] = tx.contractActions ?? []
  const ours = actions.filter(
    (a) => String(a.address).toLowerCase() === CONTRACT.toLowerCase(),
  )
  if (ours.length === 0) {
    const seen = actions.map((a) => String(a.address).slice(0, 12)).join(', ') || 'none'
    return {
      ...base,
      block,
      verdict: 'wrong-contract',
      detail: `touches no LOWBALL contract (saw: ${seen})`,
    }
  }

  const entryPoints = ours.map((a) => decodeEntryPoint(a.entryPoint)).filter(Boolean) as string[]
  if (!entryPoints.includes('placeBid')) {
    return {
      ...base,
      block,
      entryPoint: entryPoints[0] ?? null,
      verdict: 'not-a-bid',
      detail: `on our contract but the call was ${entryPoints.join('/') || 'a deploy'}, not placeBid`,
    }
  }
  return { ...base, block, entryPoint: 'placeBid', verdict: 'verified', detail: 'placeBid on the live contract' }
}

const markdownTable = (results: Result[]): string => {
  const verified = results.filter((r) => r.verdict === 'verified')
  const head = [
    '| Wallet address | Tx hash | Drop | Date | Verified |',
    '|---|---|---|---|---|',
  ]
  const rows = verified.map(
    (r) =>
      `| \`${r.address}\` | \`${r.txHash}\` | ${r.dropId || '—'} | ${r.date || '—'} | ✅ block ${r.block} |`,
  )
  return [...head, ...rows].join('\n')
}

async function main() {
  const args = process.argv.slice(2)
  const mdFlag = args.indexOf('--markdown')
  const mdPath = mdFlag >= 0 ? args[mdFlag + 1] : null
  const csvPath = args.find((a) => !a.startsWith('--') && a !== mdPath)
  if (!csvPath) throw new Error('Usage: npm run verify-users -- <users.csv> [--markdown <out.md>]')

  const { name: network, config } = resolveNetwork()
  const endpoint = config.indexer

  const rows = toRows(readFileSync(resolve(csvPath), 'utf-8'))
  console.log(`Verifying ${rows.length} row(s) against ${CONTRACT.slice(0, 12)}… on ${network}\n`)

  const results: Result[] = []
  for (const row of rows) {
    const result = await verify(endpoint, row)
    const mark = result.verdict === 'verified' ? '✅' : '❌'
    console.log(`${mark} ${(row.address || '(no address)').slice(0, 24).padEnd(26)} ${result.verdict}`)
    if (result.verdict !== 'verified') console.log(`     ${result.detail}`)
    results.push(result)
  }

  const verified = results.filter((r) => r.verdict === 'verified')
  // A user is a distinct wallet, not a distinct row — one person submitting
  // twice is one user.
  const wallets = new Set(verified.map((r) => r.address.toLowerCase()))

  console.log(`\n${'─'.repeat(56)}`)
  console.log(`rows:            ${results.length}`)
  console.log(`verified rows:   ${verified.length}`)
  console.log(`distinct users:  ${wallets.size}   <- the number L5/L6 is judged on`)
  const failed = results.length - verified.length
  if (failed > 0) {
    console.log(`unverified:      ${failed}`)
    const byVerdict = new Map<string, number>()
    for (const r of results) {
      if (r.verdict === 'verified') continue
      byVerdict.set(r.verdict, (byVerdict.get(r.verdict) ?? 0) + 1)
    }
    for (const [verdict, n] of byVerdict) console.log(`  ${verdict}: ${n}`)
  }

  if (mdPath) {
    const out = resolve(mdPath)
    const body = `<!-- GENERATED by ops/src/verify-users.ts — do not edit by hand. -->
# Verified users

Every row below was checked against the Preprod indexer: the transaction exists,
it touches the live LOWBALL contract \`${CONTRACT}\`, and its entry point is
\`placeBid\`. Rows that failed any of those checks are not listed.

**Distinct verified wallets: ${wallets.size}** (from ${results.length} submitted row(s)).

Regenerate with:

\`\`\`bash
cd ops && MIDNIGHT_NETWORK=preprod npm run verify-users -- <export.csv> --markdown ../docs/USERS.md
\`\`\`

${markdownTable(results)}
`
    writeFileSync(out, body)
    console.log(`\nWrote ${out}`)
  }
}

main().catch((e) => {
  console.error(e instanceof Error ? (e.stack ?? e.message) : e)
  process.exit(1)
})
